[package]
name = "fappa"
version = "0.1.0"
authors = ["Chris West (Faux) <git@goeswhere.com>"]

[dependencies]
clap = "2.31"
failure = "0.1"
fs_extra = "1"
futures = "0.1"
git2 = "0.7"
handlebars = "1.0.0-beta.1"
rustc-serialize = "0.3"
serde = "1"
serde_derive = "1"
serde_json = "1"
shiplift = "0.4"
tempdir = "0.3"
tokio = "0.1"
toml = "0.4"
url = "1"
walkdir = "2"
