[package]
name = "fappa"
version = "0.1.0"
authors = ["Chris West (Faux) <git@goeswhere.com>"]

edition = "2018"

[dependencies]
clap = "2.31"
failure = "0.1"
fs_extra = "1"
git2 = "0.8"
serde = "1"
serde_derive = "1"
serde_json = "1"
tempfile = "3"
toml = "0.4"
url = "1"
walkdir = "2"
