[package]
name = "fappa"
version = "0.1.0"
authors = ["Chris West (Faux) <git@goeswhere.com>"]

edition = "2018"

[dependencies]
clap = "2.31"
failure = "0.1"
fs_extra = "1"
git2 = "0.7"
handlebars = "1.0.0-beta.1"
rustc-serialize = "0.3"
serde = "1"
serde_derive = "1"
serde_json = "1"
tempdir = "0.3"
toml = "0.4"
url = "1"
walkdir = "2"

[dependencies.shiplift]
# HEAD just after 0.3.0; no reason except I'm probably going to be hacking it
git = "https://github.com/FauxFaux/shiplift"
rev = "06a01b8ebfbeecfab3211e0d273e4790adb904b7"
