[[package]]
name = "libftdi1-dev"

build_dep = [
    "cmake",

    "libusb-1.0-0-dev",
    "libconfuse-dev",

    "swig",
    "python-dev",

    "libboost-dev",
    "libboost-test-dev",

    "doxygen",
]
dep = [
]

source = [
  "CLONE git://developer.intra2net.com/libftdi?rev=d5c1622a2ff0c722c0dc59533748489b45774e55 libftdi",
]
build = [
  "WORKDIR libftdi",
  "CMAKE",
]
install = [
  "RUN make install",
]

include_files = [
  "/usr/local/**",
]

exclude_files = [
  "/build/**",
]


[[package]]
name = "libsigrok"

build_dep = [
    "libglib2.0-dev",
    "libzip-dev",

    # optional
    "libftdi1-dev",
    "libglibmm-2.4-dev",
    "libieee1284-3-dev",
    "libserialport-dev",
    "libusb-1.0-0-dev",

    "python-dev",
    "python-gi-dev",
    "python-setuptools",
    "python-numpy",

    "ruby-dev",

    # makes autoconf pick up python
    "autoconf-archive",

    "check",
    "doxygen",
    "swig",
]
dep = []

source = [
  "CLONE git://sigrok.org/libsigrok?rev=56bcbbffd059b0049e530481e2842a5ac48fd447 libsigrok",
]
build = [
  "WORKDIR libsigrok",
  "AUTORECONF",
]
install = [
  "RUN make install",
]

include_files = [
  "/usr/local/**",
]

exclude_files = [
  "/build/**",
]
