[[package]]
name = "libsigrok"

build_dep = [
    "libglib2.0-dev",
    "libzip-dev",

    # optional
    "libglibmm-2.4-dev",
    "libftdi1-dev",
    "libusb-1.0-0-dev",
    "libieee1284-3-dev",

    "python-dev",
    "python-gi-dev",
    "python-setuptools",
    "python-numpy",

    # makes autoconf pick up python
    "autoconf-archive",

    "check",
    "doxygen",
    "swig",
]
dep = []

source = [
  "CLONE git://sigrok.org/libsigrok?rev=090f1e1e5478ea15baa3731fefbd4aff9be78c77 libsigrok",
]
build = [
  "WORKDIR libsigrok",
  "AUTORECONF",
]
install = [
  "RUN make install",
]

include_files = [
  "/usr/local/**",
]

exclude_files = [
  "/build/**",
]
